// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleAppT.Models;

namespace VehicleAppT.Migrations
{
    [DbContext(typeof(VehicleAppTContext))]
    [Migration("20190805192804_vehicleapptcontext")]
    partial class vehicleapptcontext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleAppT.Models.VModel", b =>
                {
                    b.Property<int>("MID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model");

                    b.HasKey("MID");

                    b.ToTable("VModel");
                });

            modelBuilder.Entity("VehicleAppT.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LicensePNr");

                    b.Property<int>("MID");

                    b.Property<string>("VinMark");

                    b.HasKey("Id");

                    b.HasIndex("MID");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("VehicleAppT.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleAppT.Models.VModel", "VModel")
                        .WithMany()
                        .HasForeignKey("MID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
